export const AUTH_ERROR_CODES = {
  CONFIG_MISSING: "AUTH_CONFIG_MISSING",
  POPUP_CLOSED: "AUTH_POPUP_CLOSED",
  INVALID_PHONE: "AUTH_INVALID_PHONE",
  INVALID_OTP: "AUTH_INVALID_OTP",
  OTP_EXPIRED: "AUTH_OTP_EXPIRED",
  TOO_MANY_REQUESTS: "AUTH_TOO_MANY_REQUESTS",
  NETWORK: "AUTH_NETWORK",
  RECAPTCHA: "AUTH_RECAPTCHA",
  UNKNOWN: "AUTH_UNKNOWN",
} as const;

export type AuthErrorCode =
  (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];
